# corpus facotry

训练语料预处理

In [1]:
# 环境配置
%cd /playground/sgd_deep_learning/sgd_nlp/
import sys 
sys.path.append('./python')

/playground/sgd_deep_learning/sgd_nlp


In [2]:
from sgd_nlp.embedding import CorpusFactoryGlove, CorpusFactorySkipGram, CorpusFactoryCbow

import torch
import os

### SkipGram

In [3]:
data_home = r'./data/'
sub_dir = r'friends/season01'

corpus_dir = os.path.join(data_home, sub_dir)
print('CURRENT PATH:\t', corpus_dir)
win_width = 11
pair_symmetric = False
batch_num = 1024
neg_k = 5

corpus_factory = CorpusFactorySkipGram(corpus_dir)

device = torch.device('cuda')
train_data = corpus_factory.training_batch(batch_num, win_width, neg_k,
                                device=device)
print(train_data)
print(type(train_data), train_data.shape)


CURRENT PATH:	 ./data/friends/season01
tensor([[   1,   75, 3081,  ..., 1132, 2205, 5893],
        [   1,   23, 5302,  ...,  354, 1565, 6332],
        [   1,    1, 2586,  ..., 2560, 4620,  333],
        ...,
        [  13,  126, 2341,  ..., 6056, 2570, 1830],
        [  13,    1,  854,  ..., 1228, 3767, 1605],
        [ 495,   17, 4268,  ..., 3332, 5569, 4205]], device='cuda:0')
<class 'torch.Tensor'> torch.Size([1024, 7])


### Cbow

In [4]:
data_home = r'./data/'
sub_dir = r'friends/season01'

corpus_dir = os.path.join(data_home, sub_dir)
print('CURRENT PATH:\t', corpus_dir)
win_width = 11
pair_symmetric = False
batch_num = 1024
neg_k = 5

corpus_factory = CorpusFactorySkipGram(corpus_dir)

device = torch.device('cuda')
train_data = corpus_factory.training_batch(batch_num, win_width, neg_k,
                                device=device)
print(train_data)
print(type(train_data), train_data.shape)

CURRENT PATH:	 ./data/friends/season01
tensor([[   1,   75, 1549,  ..., 1248, 5149, 6066],
        [   1,  147, 3204,  ...,  413, 5457, 5888],
        [   1,  746, 3571,  ..., 5003,  981,  321],
        ...,
        [   3,  675,  254,  ..., 2460, 5313, 3958],
        [   3,   18, 5396,  ..., 5717, 3690, 5731],
        [   3, 1246, 2384,  ..., 1821, 2598, 1675]], device='cuda:0')
<class 'torch.Tensor'> torch.Size([1024, 7])


### Cbow

In [5]:
data_home = r'./data/'
sub_dir = r'friends/season01'

corpus_dir = os.path.join(data_home, sub_dir)
print('CURRENT PATH:\t', corpus_dir)
win_width = 11
pair_symmetric = False
batch_num = 1024
neg_k = 5

corpus_factory = CorpusFactoryCbow(corpus_dir)

device = torch.device('cuda')
train_data = corpus_factory.training_batch(batch_num, win_width, neg_k,
                                device=device)
print(train_data)
print(type(train_data), train_data.shape)

CURRENT PATH:	 ./data/friends/season01
tensor([[  56,  168,  173,  ..., 4198, 2093, 3410],
        [ 168,   56,  173,  ..., 4581, 3879, 2604],
        [ 173,   56,  168,  ..., 5023, 2821, 4196],
        ...,
        [  16,   61,   14,  ...,  960, 4910, 4088],
        [  61,   16,   14,  ..., 5617, 4192, 1134],
        [  14,   16,   61,  ..., 5001, 4293, 1507]], device='cuda:0')
<class 'torch.Tensor'> torch.Size([1024, 16])


### Glove

In [6]:
data_home = r'./data/'
sub_dir = r'friends/season01'

corpus_dir = os.path.join(data_home, sub_dir)
print('CURRENT PATH:\t', corpus_dir)
win_width = 11
pair_symmetric = False
batch_num = 1024
neg_k = 5

corpus_factory = CorpusFactoryGlove(corpus_dir,win_width=win_width, pair_symmetric=pair_symmetric)

device = torch.device('cuda')
train_data = corpus_factory.training_batch(batch_num, device=device)
print(train_data)
print(type(train_data), train_data.shape)

CURRENT PATH:	 ./data/friends/season01
tensor([[ 810,   13,    1],
        [5214, 1539,    1],
        [1685,    1,    1],
        ...,
        [3987,    3,    1],
        [2754,   31,    2],
        [2700, 2701,    1]], device='cuda:0')
<class 'torch.Tensor'> torch.Size([1024, 3])


## playground

In [7]:
from collections import Counter

tokens = [1,2,3,1]
freqs1 = sorted(Counter(tokens).items(), key=lambda x: x[1], reverse=True)
print(freqs1)

def f1(tokens):
    for x in tokens:
        yield x
    
g1 = f1(tokens)
freqs2 = sorted(Counter(g1).items(), key=lambda x: x[1], reverse=True)
print(freqs2, type(g1))


[(1, 2), (2, 1), (3, 1)]
[(1, 2), (2, 1), (3, 1)] <class 'generator'>


In [8]:
from sgd_nlp.common.read_file import yield_tokens_from_docs
from collections import Counter

def _init_documents(docs_dir):
    # 递归枚举所有子文件路径
    def recursive_list_files(root_dir):
        f_list = []
        for root, dirs, files in os.walk(root_dir, topdown=False):
            f_list += ([os.path.join(root, fi) for fi in files])
            if dirs:  # 非空
                for di in dirs:
                    f_list += (recursive_list_files(os.path.join(root, di)))
        return f_list

    if os.path.isfile(docs_dir):  # case1： 单个文件
        return [docs_dir]
    else: # case2：递归遍历文件夹
        return recursive_list_files(docs_dir)
    
docs = _init_documents(corpus_dir)
print(docs)
        
tokens = yield_tokens_from_docs(docs)
print(tokens)
# print("[Debug]", [x for x in tokens][:5], type(tokens))

_token_freqs = sorted(Counter(tokens).items(), key=lambda x: x[1], reverse=True)
print(_token_freqs)


['./data/friends/season01/101.txt', './data/friends/season01/102.txt', './data/friends/season01/103.txt', './data/friends/season01/104.txt', './data/friends/season01/105.txt', './data/friends/season01/106.txt', './data/friends/season01/107.txt', './data/friends/season01/108.txt', './data/friends/season01/109.txt', './data/friends/season01/110.txt', './data/friends/season01/111.txt', './data/friends/season01/112.txt', './data/friends/season01/113.txt', './data/friends/season01/114.txt', './data/friends/season01/115.txt', './data/friends/season01/116.txt', './data/friends/season01/118.txt', './data/friends/season01/119.txt', './data/friends/season01/120.txt', './data/friends/season01/121.txt', './data/friends/season01/122.txt', './data/friends/season01/123.txt', './data/friends/season01/124.txt']
<generator object yield_tokens_from_docs at 0x7f2fd14f5620>
[('I', 2002), ('the', 1952), ('you', 1485), ('and', 1399), ('a', 1329), ('to', 1319), ('Ross:', 922), ('Monica:', 838), ('Rachel:', 80